$ANSIBLE_VAULT;1.1;AES256
31326430623034663434616236623065616564636339343935646165366133626439373531373232
6162363832666261303937636235663435636638666231320a633164343638383335383262376434
39343033666538356632316632363663666566393538323431613635383130383763653138383363
6333343363363965300a373636323164356564353635663365336665346334383837623837323663
30613239393430653034303833336130303166393731313865646665366638656136653736653765
39386166626636623334356464336261366434303137613733373532376133613064623132616435
30323737386165383932383430356131373931653034396263346131336537656430313139633036
61373565326337613263303337383165663665393264386338303465323061393738363765636461
62316565613531343830393766346530306364353431613232623665393731376633386433323632
64306663613161346530326437346563306166333235323937323630326134303961663231643133
66396530353434396538396363346233323031666130333861666230323263383538616237623139
37333861613862303466363862383566633461353161663034376432356261653662653762386161
32303834393432396633633466613234336139326332353338336235626631393063303637373939
36653861363131323131323662653238393263393463333436303536353661666631316361326638
62393337633864656563363765323166303263316238353933666161303337393161306662363335
34633862326661383561656536326161656439396637626637363039623939376430323964666239
64636638333563663438343963656164313434343437396539316162313836636637386237376638
66666562303864303066386334646361346637363539623134363664663333393138643831353237
33626333303762393036363165336266653931353664633135653538393666396432336530383564
61336432323065323436363463353537393461626566323538356433396564633532343063666533
64363639383630376533353537313438633937353535633236353735316532643739
